Draft, changing state
unosquare/uno-dashboard-ux pull request #155
Opened 2024-03-06 22:31 UTC by byAall

First try at changing the state to make a rework of the functionality

2024-03-07 21:12 UTC, byAall commented
Now, the method responsible for creating alerts has a third parameter: isTimed. To enable former default functionality (auto dissmisible) this parameter has to be false, otherwise the alert won't go unless its clicked. 
![image](https://github.com/unosquare/uno-dashboard-ux/assets/108778646/2a2f608e-8fba-4159-9f02-ba1e8c169499)

2024-03-07 21:17 UTC, geoperez requested changes

2024-03-07 21:17 UTC, geoperez commented on src/Alert/index.tsx
> +            <p></p>
??

2024-03-08 13:38 UTC, geoperez approved these changes

2024-03-08 13:38 UTC, merged